/**
 * Persisted completed-game document (one per finished game).
 *
 * Written exactly once when a game reaches FINAL. Loading an already-FINAL save
 * must never create a new GameDoc.
 */
export interface GameDoc {
  /**
   * Primary key — the `gameInstanceId` stored in `State` for the completed run.
   * Using `gameInstanceId` (not `saveId`) ensures that loading any mid-game
   * save slot from the same run and finishing it does NOT produce a second entry.
   */
  id: string;
  /** Wall-clock timestamp when the game was committed (ms since epoch). */
  playedAt: number;
  /** PRNG seed used for this game. */
  seed: string;
  /** RNG state captured at game-over for replay verification. */
  rngState: number | null;
  homeTeamId: string;
  awayTeamId: string;
  homeScore: number;
  awayScore: number;
  /** Number of innings played (9 normally; more for extras). */
  innings: number;
  /** The save ID (`SaveDoc.id`) that triggered the commit — for debug/traceability only. */
  committedBySaveId?: string;
  schemaVersion: number;
}

/**
 * Batting statistics for a single player in a single completed game.
 *
 * playerKey rules (v1):
 *   - Custom-team players: `globalPlayerId` when available (team-independent, so
 *     career stats follow the player across team moves). Falls back to
 *     `${teamId}:${playerId}` for legacy players that predate the v3 migration.
 *   - Stock / generated-team players: `${teamId}:${playerId}` using the player's
 *     stable roster ID (same ID generated by generateRoster for that team). Stock
 *     players cannot move teams, so team-scoping is permanent and correct.
 *   - Substituted players are recorded under their own playerKey, not the replaced slot.
 *   - Future trade/free-agent work can continue using `globalPlayerId` as-is — old
 *     rows keep their original playerKey so existing history remains intact.
 */
export interface PlayerGameStatDoc {
  /**
   * Primary key — composite: `${gameId}:${teamId}:${playerKey}`.
   * The composite format ensures global uniqueness without a separate UUID.
   */
  id: string;
  /** FK → GameDoc.id */
  gameId: string;
  teamId: string;
  opponentTeamId: string;
  /**
   * Stable cross-game identity string.
   * Custom-team players: `globalPlayerId` (team-independent) when available;
   * falls back to `${teamId}:${playerId}` for pre-v3-migration players.
   * Stock/generated-team players: `${teamId}:${playerId}`.
   */
  playerKey: string;
  /** TeamPlayer.id at the time of the game — for display/debug; may differ from playerKey. */
  playerId: string;
  /** Player name captured at game time — so history is readable even if the name changes later. */
  nameAtGameTime: string;
  role: "batter" | "pitcher";
  batting: {
    atBats: number;
    hits: number;
    walks: number;
    strikeouts: number;
    rbi: number;
    singles: number;
    doubles: number;
    triples: number;
    homers: number;
    /** Sacrifice flies: plate appearances where a caught fly ball drove in a run (PA but not AB).
     * Optional for backward compatibility — legacy docs written before this field was added will
     * not have it; all consumers must fall back to `?? 0`. */
    sacFlies?: number;
  };
  /** Wall-clock timestamp when this row was created (ms since epoch). */
  createdAt: number;
  schemaVersion: number;
}

/**
 * Pitching statistics for a single pitcher in a single completed game.
 *
 * playerKey rules match PlayerGameStatDoc — globalPlayerId for custom-team pitchers,
 * `${teamId}:${pitcherId}` for stock/generated-team pitchers.
 *
 * Outs are stored as integers; display IP as `Math.floor(outsPitched/3).Y` where
 * Y = outsPitched % 3.
 *
 * v1 simplification: earnedRuns = runsAllowed (error-tracking not yet implemented).
 */
export interface PitcherGameStatDoc {
  /**
   * Primary key — composite: `${gameId}:${teamId}:${pitcherKey}`.
   * Guarantees global uniqueness and idempotent inserts.
   */
  id: string;
  /** FK → GameDoc.id */
  gameId: string;
  teamId: string;
  opponentTeamId: string;
  /**
   * Stable cross-game identity string (mirrors PlayerGameStatDoc.playerKey rules).
   * Custom-team pitchers: globalPlayerId when available.
   * Stock/generated-team pitchers: `${teamId}:${pitcherId}`.
   */
  pitcherKey: string;
  /** Roster player ID at game time — for display/debug. */
  pitcherId: string;
  /** Pitcher name captured at game time for readable history. */
  nameAtGameTime: string;
  /** Total outs recorded while this pitcher was in the game. Display as X.Y (Y = outsPitched%3). */
  outsPitched: number;
  /** Total batters faced. */
  battersFaced: number;
  /**
   * Total pitch events thrown to batters (balls, strikes, fouls, balls in play, intentional walks).
   * Uses the simulation's pitch-event model: an intentional walk is a single event (IBB = 1),
   * not four separate pitches as in real-world pitch counts.
   */
  pitchesThrown: number;
  /** Hits allowed by this pitcher. */
  hitsAllowed: number;
  /** Walks (and intentional walks) allowed. */
  walksAllowed: number;
  /** Strikeouts recorded (batters K'd). */
  strikeoutsRecorded: number;
  /** Home runs allowed. */
  homersAllowed: number;
  /** Runs allowed (all, not just earned). */
  runsAllowed: number;
  /**
   * Earned runs. v1 approximation: equals runsAllowed.
   * Will be refined when error/earned-run tracking is added.
   */
  earnedRuns: number;
  /** Save recorded (1) or not (0). See SV rules in computePitcherGameStats.ts. */
  saves: number;
  /** Hold recorded (1) or not (0). */
  holds: number;
  /** Blown save recorded (1) or not (0). */
  blownSaves: number;
  /** Wall-clock timestamp when this row was created (ms since epoch). */
  createdAt: number;
  schemaVersion: number;
}

/** Portable signed export format for completed-game history.
 *
 * formatVersion 1 — original format (no pitcherGameStats).
 * formatVersion 2 — adds pitcherGameStats to the payload.
 * The import function accepts both versions; the export function always produces v2.
 */
export interface ExportedGameHistory {
  type: "gameHistory";
  formatVersion: 1 | 2;
  exportedAt: string;
  payload: {
    games: GameDoc[];
    playerGameStats: PlayerGameStatDoc[];
    /** Only present in v2+ bundles; undefined for v1 legacy imports. */
    pitcherGameStats?: PitcherGameStatDoc[];
    /** Team IDs referenced by stats rows — must exist locally for import to succeed. */
    requiredTeamIds: string[];
  };
  /** FNV-1a 32-bit signature of GAME_HISTORY_EXPORT_KEY + JSON.stringify(payload) */
  sig: string;
}

/** Summary returned after importing a game history bundle. */
export interface ImportGameHistoryResult {
  gamesCreated: number;
  gamesSkipped: number;
  statsCreated: number;
  statsSkipped: number;
  pitcherStatsCreated: number;
  pitcherStatsSkipped: number;
}

// ── Team Career Aggregates ────────────────────────────────────────────────────

/** Aggregated team career statistics derived from completed games. */
export interface TeamCareerSummary {
  gamesPlayed: number;
  wins: number;
  losses: number;
  /** Number of tied games (rs === ra). Ties are excluded from W/L% calculation. */
  ties: number;
  /** Win percentage (0–1), computed as wins / (wins + losses), excluding ties. */
  winPct: number;
  runsScored: number;
  runsAllowed: number;
  /** RS − RA */
  runDiff: number;
  /** Runs scored per game. */
  rsPerGame: number;
  /** Runs allowed per game. */
  raPerGame: number;
  /** Current streak string (e.g. "W3", "L2", "T1", or "-" when no games played). */
  streak: string;
  /** W-L-T record from the last 10 games played. */
  last10: { wins: number; losses: number; ties: number };
}

/** A single batting leader entry for a team. */
export interface BattingLeader {
  playerKey: string;
  nameAtGameTime: string;
  /** The stat value (e.g. HR count, batting average, RBI count). */
  value: number;
  gamesPlayed: number;
}

/** A single pitching leader entry for a team. */
export interface PitchingLeader {
  pitcherKey: string;
  nameAtGameTime: string;
  /** The stat value (e.g. ERA, saves, strikeouts). */
  value: number;
  gamesPlayed: number;
}
