import * as React from "react";

import { useGameContext } from "@context/index";
import { GameHistoryStore } from "@storage/gameHistoryStore";
import type { PlayerGameStatDoc } from "@storage/types";
import { appLog } from "@utils/logger";
import { getRngState, getSeed } from "@utils/rng";
import { generateRoster } from "@utils/roster";
import { computeBattingStatsFromLogs } from "@utils/stats/computeBattingStatsFromLogs";

/**
 * Builds the playerKey for cross-game identity.
 *
 * v1 rules:
 *   - Custom-team players: `${teamId}:${playerId}` (composite from CustomTeamDoc).
 *   - Stock / generated-team players: `${teamId}:${playerId}` using the stable
 *     roster ID generated by generateRoster for that team seed.
 *   - Substituted players are recorded under their own playerKey.
 *   - Future trade/free-agent work can evolve this scheme — old rows keep their
 *     original playerKey, so existing history remains intact.
 */
const buildPlayerKey = (teamId: string, playerId: string): string => `${teamId}:${playerId}`;

/**
 * Hooks into the game's gameOver state and commits a completed game to RxDB
 * exactly once per game session.
 *
 * Idempotency is enforced at two levels:
 *   1. Session-level: a `committedRef` is set to true after the first commit
 *      so the hook never writes twice in the same browser session, even if
 *      `gameOver` briefly toggles (e.g. after a load).
 *   2. DB-level: `GameHistoryStore.commitCompletedGame` checks for an existing
 *      GameDoc with the same `saveId` before writing, so a page reload followed
 *      by re-watching an already-FINAL save cannot produce duplicate rows.
 *
 * Loading an already-FINAL save must NOT trigger a new commit. The hook guards
 * against this by checking `wasAlreadyFinalOnLoad` — set when the save is
 * restored with `gameOver === true` from `stateSnapshot`.
 */
export const useGameHistorySync = (
  rxSaveIdRef: React.MutableRefObject<string | null>,
  /** Pass true when the save being loaded was already in FINAL state. */
  wasAlreadyFinalOnLoad: boolean,
): void => {
  const gameContext = useGameContext();
  const { gameOver } = gameContext;

  // True after we have successfully committed this game session.
  const committedRef = React.useRef(false);
  // Capture the wasAlreadyFinalOnLoad flag in a ref so the effect sees the latest value.
  const alreadyFinalRef = React.useRef(wasAlreadyFinalOnLoad);
  alreadyFinalRef.current = wasAlreadyFinalOnLoad;

  const gameStateRef = React.useRef(gameContext);
  gameStateRef.current = gameContext;

  React.useEffect(() => {
    if (!gameOver) return;
    // Skip if: already committed, or the game was already FINAL when it was loaded.
    if (committedRef.current || alreadyFinalRef.current) return;

    const saveId = rxSaveIdRef.current;
    if (!saveId) return;

    committedRef.current = true;

    const state = gameStateRef.current;

    // Build stat rows for both teams.
    const statRows: Omit<PlayerGameStatDoc, "id" | "schemaVersion" | "createdAt">[] = [];

    for (const teamIdx of [0, 1] as const) {
      const teamId = state.teams[teamIdx];
      const opponentTeamId = state.teams[teamIdx === 0 ? 1 : 0];
      const teamStats = computeBattingStatsFromLogs(
        teamIdx,
        state.playLog,
        state.strikeoutLog,
        state.outLog,
      );

      // Build a playerId → name map for this team.
      const roster = generateRoster(teamId);
      const order =
        state.lineupOrder[teamIdx].length > 0
          ? state.lineupOrder[teamIdx]
          : roster.batters.map((p) => p.id);
      const idToName = new Map(roster.batters.map((p) => [p.id, p.name]));

      for (const [key, batting] of Object.entries(teamStats)) {
        // Skip slot-fallback keys (no playerKey available for legacy entries).
        if (key.startsWith("slot:")) continue;
        const playerId = key;
        const playerKey = buildPlayerKey(teamId, playerId);

        // Resolve name: check lineupOrder index, then roster map, fallback to playerId.
        const slotIdx = order.indexOf(playerId);
        const nameAtGameTime =
          state.playerOverrides[teamIdx][playerId]?.nickname?.trim() ||
          idToName.get(playerId) ||
          (slotIdx >= 0 ? `Batter ${slotIdx + 1}` : playerId);

        statRows.push({
          gameId: saveId,
          teamId,
          opponentTeamId,
          playerKey,
          playerId,
          nameAtGameTime,
          role: "batter",
          batting,
        });
      }
    }

    const gameMeta = {
      playedAt: Date.now(),
      seed: getSeed()?.toString(36) ?? "",
      rngState: getRngState(),
      homeTeamId: state.teams[1],
      awayTeamId: state.teams[0],
      homeScore: state.score[1],
      awayScore: state.score[0],
      innings: state.inning,
    };

    GameHistoryStore.commitCompletedGame(saveId, gameMeta, statRows).catch((err) => {
      appLog.error("useGameHistorySync: failed to commit completed game", err);
      // Reset the committed flag so a subsequent attempt can retry.
      committedRef.current = false;
    });
  }, [gameOver, rxSaveIdRef]);

  // Reset the committed flag when a new save is loaded (rxSaveIdRef changes).
  // This ensures a new game session can be committed even within the same
  // browser tab.
  const prevSaveIdRef = React.useRef<string | null>(null);
  React.useEffect(() => {
    const current = rxSaveIdRef.current;
    if (current !== prevSaveIdRef.current) {
      prevSaveIdRef.current = current;
      committedRef.current = false;
    }
  });
};
