let seed: number | null = null;
let rng: (() => number) | null = null;
/** The current value of `a` inside the mulberry32 closure — captured after every call. */
let rngInternalA: number | null = null;

const mulberry32 = (a: number) => (): number => {
  a += 0x6d2b79f5;
  rngInternalA = a;
  let t = a;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

const parseSeed = (seedString: string): number | null => {
  const trimmed = seedString.trim();
  if (!trimmed) return null;
  const radix = /[a-z]/i.test(trimmed) ? 36 : 10;
  const parsed = parseInt(trimmed, radix);
  if (!Number.isFinite(parsed)) return null;
  return parsed >>> 0;
};

const generateSeed = (): number => {
  if (typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function") {
    const buf = new Uint32Array(1);
    crypto.getRandomValues(buf);
    return buf[0];
  }
  return ((Math.random() * 0xffffffff) ^ Date.now()) >>> 0;
};

/** Tracks the last seed generated by generateFreshSeed to guarantee uniqueness on rapid calls. */
let lastFreshSeed: number | null = null;

/**
 * Generates a fresh random seed value without affecting the current PRNG state.
 * Unlike `getSeed()`, this creates a brand-new seed value independent of the
 * current PRNG state, making it suitable for initializing seed inputs (e.g. the
 * New Game screen) without committing the value to the global RNG.
 *
 * Guaranteed to return a different value from the previous call even when called
 * in rapid succession (e.g. consecutive page opens within the same millisecond).
 * After up to 3 random retries, falls back to a deterministic rotation
 * (lastSeed + 1) to ensure uniqueness in the extremely unlikely event that all
 * random attempts produce a collision.
 */
export const generateFreshSeed = (): number => {
  let s = generateSeed();
  // Loop to guarantee a different value even on rapid successive calls.
  // With crypto.getRandomValues, collision probability is 1/2^32 per attempt;
  // three attempts reduce the chance to negligible (< 1 in 10^28).
  const maxRetries = 3;
  let retries = 0;
  while (s === lastFreshSeed && retries < maxRetries) {
    s = generateSeed();
    retries++;
  }
  // Deterministic fallback: if all retries still collided (extremely unlikely),
  // rotate by 1 to unconditionally guarantee a different value.
  if (s === lastFreshSeed) {
    s = ((lastFreshSeed ?? 0) + 1) >>> 0;
  }
  lastFreshSeed = s;
  return s;
};

/**
 * Initializes the PRNG with a fresh random seed if it has not been initialized yet.
 * Safe to call multiple times — subsequent calls are no-ops.
 */
export const initSeed = (): number | null => {
  if (seed !== null && rng) {
    return seed;
  }
  const nextSeed = generateSeed();
  seed = nextSeed;
  rng = mulberry32(seed);
  rngInternalA = seed; // pre-call state
  return seed;
};

export const getSeed = (): number | null => {
  if (seed === null) {
    initSeed();
  }
  return seed;
};

export const random = (): number => {
  if (!rng) {
    initSeed();
  }
  if (!rng) {
    throw new Error("Random generator not initialized");
  }
  return rng();
};

/**
 * Returns the current internal PRNG state (the value of `a` after the last
 * `random()` call, or the initial seed if no call has been made yet).
 * Store this alongside game state so the PRNG position can be fully restored.
 */
export const getRngState = (): number | null => rngInternalA;

/**
 * Restores the PRNG to a previously captured state so that the next
 * `random()` call produces the same value it would have in the original game.
 */
export const restoreRng = (state: number): void => {
  rng = mulberry32(state);
  rngInternalA = state;
};

/**
 * Sets the stored seed from a save's seed string (base-36 or decimal) without
 * touching the PRNG state.  Always call `restoreRng(snap.rngState)` immediately
 * after so that `getSeed()` / `currentSeedStr()` / `findMatchedSave` all reflect
 * the restored game's identity rather than the random startup seed.
 */
export const restoreSeed = (seedStr: string): void => {
  const parsed = parseSeed(seedStr);
  if (parsed !== null) seed = parsed;
};

/**
 * Re-initializes the PRNG from a caller-supplied seed string (base-36 or
 * decimal).  Unlike `initSeed`, this can be called at any time —
 * e.g. when the user submits the New Game form (the seed field is
 * pre-populated via `generateFreshSeed()` but may be edited by the user).
 *
 * If `seedStr` is blank or unparseable a fresh random seed is generated.
 *
 * Returns the numeric seed that was actually applied.
 */
export const reinitSeed = (seedStr: string): number => {
  const parsed = parseSeed(seedStr);
  const nextSeed = parsed ?? generateSeed();
  seed = nextSeed;
  rng = mulberry32(seed);
  rngInternalA = seed;
  return seed;
};
