import type { TeamPlayer } from "@storage/types";

import { LAKEWOOD_LEGENDS } from "./demoTeamLakewood";
import { RIVERSIDE_ROCKETS } from "./demoTeamRiverside";

/**
 * Player definition used only in demo team seeding.
 *
 * Derived from `TeamPlayer` (minus store-managed and editor-only fields) so
 * TypeScript will flag any new required `TeamPlayer` fields that are missing
 * here.  `id` is assigned by the demo seeding hook via `generatePlayerId()`.
 * `playerSeed` and `fingerprint` are generated by `CustomTeamStore` during
 * sanitization.  `position` and `handedness` are made required (they are
 * optional on `TeamPlayer`) so the compiler prevents demo players from being
 * added without them.
 */
export type DemoPlayerDef = Omit<
  TeamPlayer,
  | "id" // assigned at seeding time via generatePlayerId()
  | "playerSeed" // generated and stored by CustomTeamStore
  | "fingerprint" // computed by CustomTeamStore
  | "sig" // export-only field; stripped before DB storage
  | "isBenchEligible" // editor-computed; not applicable to demo definitions
  | "isPitcherEligible" // editor-computed; not applicable to demo definitions
  | "jerseyNumber" // optional cosmetic; omitted for demo teams
> & {
  /** Narrow to the two roles used by demo teams (no "two-way" players). */
  role: "batter" | "pitcher";
  /** Required for demo players — must be set so validateCustomTeamForGame passes. */
  position: string;
  /** Required for demo players — batting handedness must always be explicit. */
  handedness: "R" | "L" | "S";
};

/** Full team definition used for demo seeding. */
export type DemoTeamDef = {
  /**
   * Deterministic RxDB document ID used when inserting the team.
   * Stable across app versions so concurrent tab seeding attempts produce a
   * predictable duplicate-key collision rather than two separate inserts.
   */
  demoId: string;
  city: string;
  name: string;
  abbreviation: string;
  lineup: DemoPlayerDef[];
  bench: DemoPlayerDef[];
  pitchers: DemoPlayerDef[];
};

/**
 * Starter teams seeded into the DB when a brand-new user launches the app
 * with an empty custom-teams collection.
 *
 * Stat constraints:
 *   Hitters  — contact, power, speed each in [40, 70], sum ≤ 150 (HITTER_STAT_CAP)
 *   Pitchers — velocity, control, movement each in [40, 70], sum ≤ 160 (PITCHER_STAT_CAP)
 *
 * Each team's full roster is defined in its own module to keep file sizes
 * manageable:
 *   - Riverside Rockets → {@link ./demoTeamRiverside}
 *   - Lakewood Legends  → {@link ./demoTeamLakewood}
 */
export const DEMO_TEAMS: DemoTeamDef[] = [RIVERSIDE_ROCKETS, LAKEWOOD_LEGENDS];
