/** Player definition used only in demo team seeding — no ID (generated by the store). */
type DemoPlayerDef = {
  name: string;
  /** Matches TeamPlayer.role values ("batter" / "pitcher"). */
  role: "batter" | "pitcher";
  batting: { contact: number; power: number; speed: number };
  pitching?: { velocity: number; control: number; movement: number };
};

/** Full team definition used for demo seeding. */
export type DemoTeamDef = {
  city: string;
  name: string;
  abbreviation: string;
  lineup: DemoPlayerDef[];
  bench: DemoPlayerDef[];
  pitchers: DemoPlayerDef[];
};

/**
 * Two starter teams seeded into the DB when a brand-new user launches the app
 * with an empty custom-teams collection.
 *
 * Stat constraints:
 *   Hitters  — contact, power, speed each in [40, 70], sum ≤ 150 (HITTER_STAT_CAP)
 *   Pitchers — velocity, control, movement each in [40, 70], sum ≤ 160 (PITCHER_STAT_CAP)
 */
export const DEMO_TEAMS: DemoTeamDef[] = [
  {
    city: "Riverside",
    name: "Rockets",
    abbreviation: "RIV",
    lineup: [
      // contact + power + speed = 150
      { name: "Marcus Rivera", role: "batter", batting: { contact: 60, power: 50, speed: 40 } },
      { name: "Jordan Hayes", role: "batter", batting: { contact: 50, power: 60, speed: 40 } },
      { name: "Tyler Brooks", role: "batter", batting: { contact: 55, power: 55, speed: 40 } },
      { name: "Devon Carter", role: "batter", batting: { contact: 45, power: 65, speed: 40 } },
      { name: "Malik Johnson", role: "batter", batting: { contact: 55, power: 50, speed: 45 } },
      { name: "Ethan Torres", role: "batter", batting: { contact: 50, power: 50, speed: 50 } },
      { name: "Sean Mitchell", role: "batter", batting: { contact: 58, power: 52, speed: 40 } },
      { name: "Aaron Pena", role: "batter", batting: { contact: 48, power: 62, speed: 40 } },
      { name: "Kyle Simmons", role: "batter", batting: { contact: 52, power: 58, speed: 40 } },
    ],
    bench: [
      { name: "Carlos Reyes", role: "batter", batting: { contact: 60, power: 50, speed: 40 } },
      { name: "Omar Diaz", role: "batter", batting: { contact: 50, power: 60, speed: 40 } },
      { name: "Justin Lee", role: "batter", batting: { contact: 55, power: 55, speed: 40 } },
      { name: "Brandon Cruz", role: "batter", batting: { contact: 53, power: 57, speed: 40 } },
    ],
    pitchers: [
      // velocity + control + movement = 160
      {
        name: "Rafael Gomez",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 60, control: 55, movement: 45 },
      },
      {
        name: "Darius Webb",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 55, control: 60, movement: 45 },
      },
      {
        name: "Lance Freeman",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 50, control: 60, movement: 50 },
      },
      {
        name: "Nathan Park",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 55, control: 55, movement: 50 },
      },
    ],
  },
  {
    city: "Lakewood",
    name: "Legends",
    abbreviation: "LAK",
    lineup: [
      // contact + power + speed = 150
      { name: "Trevor Walsh", role: "batter", batting: { contact: 58, power: 52, speed: 40 } },
      { name: "Dominic Santos", role: "batter", batting: { contact: 50, power: 60, speed: 40 } },
      { name: "Leo Martinez", role: "batter", batting: { contact: 65, power: 45, speed: 40 } },
      { name: "Patrick O'Brien", role: "batter", batting: { contact: 45, power: 65, speed: 40 } },
      { name: "Cole Henderson", role: "batter", batting: { contact: 52, power: 58, speed: 40 } },
      { name: "Ryan Nguyen", role: "batter", batting: { contact: 50, power: 50, speed: 50 } },
      { name: "Alex Patel", role: "batter", batting: { contact: 55, power: 55, speed: 40 } },
      { name: "Sean McCoy", role: "batter", batting: { contact: 48, power: 62, speed: 40 } },
      { name: "Jake Flores", role: "batter", batting: { contact: 53, power: 57, speed: 40 } },
    ],
    bench: [
      { name: "Mike Garcia", role: "batter", batting: { contact: 55, power: 55, speed: 40 } },
      { name: "Noah Williams", role: "batter", batting: { contact: 60, power: 50, speed: 40 } },
      { name: "Chris Baker", role: "batter", batting: { contact: 50, power: 60, speed: 40 } },
      { name: "Sam Turner", role: "batter", batting: { contact: 52, power: 58, speed: 40 } },
    ],
    pitchers: [
      // velocity + control + movement = 160
      {
        name: "Victor Cruz",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 65, control: 50, movement: 45 },
      },
      {
        name: "Eric Dawson",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 55, control: 60, movement: 45 },
      },
      {
        name: "Todd Morrison",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 50, control: 55, movement: 55 },
      },
      {
        name: "Jared Kim",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 60, control: 55, movement: 45 },
      },
    ],
  },
];
