import type { TeamPlayer } from "@storage/types";

/**
 * Player definition used only in demo team seeding.
 *
 * Derived from `TeamPlayer` (minus store-managed and editor-only fields) so
 * TypeScript will flag any new required `TeamPlayer` fields that are missing
 * here.  `id`, `playerSeed`, and `fingerprint` are excluded because they are
 * generated by `CustomTeamStore` at insert time.  `position` and `handedness`
 * are made required (they are optional on `TeamPlayer`) so the compiler
 * prevents demo players from being added without them.
 */
type DemoPlayerDef = Omit<
  TeamPlayer,
  | "id" // assigned at seeding time via generatePlayerId()
  | "playerSeed" // generated and stored by CustomTeamStore
  | "fingerprint" // computed by CustomTeamStore
  | "sig" // export-only field; stripped before DB storage
  | "isBenchEligible" // editor-computed; not applicable to demo definitions
  | "isPitcherEligible" // editor-computed; not applicable to demo definitions
  | "jerseyNumber" // optional cosmetic; omitted for demo teams
> & {
  /** Narrow to the two roles used by demo teams (no "two-way" players). */
  role: "batter" | "pitcher";
  /** Required for demo players — must be set so validateCustomTeamForGame passes. */
  position: string;
  /** Required for demo players — batting handedness must always be explicit. */
  handedness: "R" | "L" | "S";
};

/** Full team definition used for demo seeding. */
export type DemoTeamDef = {
  /**
   * Deterministic RxDB document ID used when inserting the team.
   * Stable across app versions so concurrent tab seeding attempts produce a
   * predictable duplicate-key collision rather than two separate inserts.
   */
  demoId: string;
  city: string;
  name: string;
  abbreviation: string;
  lineup: DemoPlayerDef[];
  bench: DemoPlayerDef[];
  pitchers: DemoPlayerDef[];
};

/**
 * Two starter teams seeded into the DB when a brand-new user launches the app
 * with an empty custom-teams collection.
 *
 * Stat constraints:
 *   Hitters  — contact, power, speed each in [40, 70], sum ≤ 150 (HITTER_STAT_CAP)
 *   Pitchers — velocity, control, movement each in [40, 70], sum ≤ 160 (PITCHER_STAT_CAP)
 */
export const DEMO_TEAMS: DemoTeamDef[] = [
  {
    demoId: "ct_demo_riv",
    city: "Riverside",
    name: "Rockets",
    abbreviation: "RIV",
    lineup: [
      // contact + power + speed = 150; each of the 9 BATTING_POSITIONS exactly once
      {
        name: "Marcus Rivera",
        role: "batter",
        batting: { contact: 60, power: 50, speed: 40 },
        position: "C",
        handedness: "R",
      },
      {
        name: "Jordan Hayes",
        role: "batter",
        batting: { contact: 50, power: 60, speed: 40 },
        position: "1B",
        handedness: "R",
      },
      {
        name: "Tyler Brooks",
        role: "batter",
        batting: { contact: 55, power: 55, speed: 40 },
        position: "2B",
        handedness: "R",
      },
      {
        name: "Devon Carter",
        role: "batter",
        batting: { contact: 45, power: 65, speed: 40 },
        position: "3B",
        handedness: "L",
      },
      {
        name: "Malik Johnson",
        role: "batter",
        batting: { contact: 55, power: 50, speed: 45 },
        position: "SS",
        handedness: "R",
      },
      {
        name: "Ethan Torres",
        role: "batter",
        batting: { contact: 50, power: 50, speed: 50 },
        position: "LF",
        handedness: "R",
      },
      {
        name: "Sean Mitchell",
        role: "batter",
        batting: { contact: 58, power: 52, speed: 40 },
        position: "CF",
        handedness: "R",
      },
      {
        name: "Aaron Pena",
        role: "batter",
        batting: { contact: 48, power: 62, speed: 40 },
        position: "RF",
        handedness: "R",
      },
      {
        name: "Kyle Simmons",
        role: "batter",
        batting: { contact: 52, power: 58, speed: 40 },
        position: "DH",
        handedness: "R",
      },
    ],
    bench: [
      {
        name: "Carlos Reyes",
        role: "batter",
        batting: { contact: 60, power: 50, speed: 40 },
        position: "C",
        handedness: "R",
      },
      {
        name: "Omar Diaz",
        role: "batter",
        batting: { contact: 50, power: 60, speed: 40 },
        position: "1B",
        handedness: "L",
      },
      {
        name: "Justin Lee",
        role: "batter",
        batting: { contact: 55, power: 55, speed: 40 },
        position: "LF",
        handedness: "R",
      },
      {
        name: "Brandon Cruz",
        role: "batter",
        batting: { contact: 53, power: 57, speed: 40 },
        position: "SS",
        handedness: "R",
      },
    ],
    pitchers: [
      // velocity + control + movement = 160
      {
        name: "Rafael Gomez",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 60, control: 55, movement: 45 },
        position: "SP",
        handedness: "R",
        pitchingRole: "SP",
      },
      {
        name: "Darius Webb",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 55, control: 60, movement: 45 },
        position: "SP",
        handedness: "L",
        pitchingRole: "SP",
      },
      {
        name: "Lance Freeman",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 50, control: 60, movement: 50 },
        position: "RP",
        handedness: "R",
        pitchingRole: "RP",
      },
      {
        name: "Nathan Park",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 55, control: 55, movement: 50 },
        position: "RP",
        handedness: "R",
        pitchingRole: "RP",
      },
    ],
  },
  {
    demoId: "ct_demo_lak",
    city: "Lakewood",
    name: "Legends",
    abbreviation: "LAK",
    lineup: [
      // contact + power + speed = 150; each of the 9 BATTING_POSITIONS exactly once
      {
        name: "Trevor Walsh",
        role: "batter",
        batting: { contact: 58, power: 52, speed: 40 },
        position: "C",
        handedness: "R",
      },
      {
        name: "Dominic Santos",
        role: "batter",
        batting: { contact: 50, power: 60, speed: 40 },
        position: "1B",
        handedness: "R",
      },
      {
        name: "Leo Martinez",
        role: "batter",
        batting: { contact: 65, power: 45, speed: 40 },
        position: "2B",
        handedness: "L",
      },
      {
        name: "Patrick O'Brien",
        role: "batter",
        batting: { contact: 45, power: 65, speed: 40 },
        position: "3B",
        handedness: "R",
      },
      {
        name: "Cole Henderson",
        role: "batter",
        batting: { contact: 52, power: 58, speed: 40 },
        position: "SS",
        handedness: "R",
      },
      {
        name: "Ryan Nguyen",
        role: "batter",
        batting: { contact: 50, power: 50, speed: 50 },
        position: "LF",
        handedness: "R",
      },
      {
        name: "Alex Patel",
        role: "batter",
        batting: { contact: 55, power: 55, speed: 40 },
        position: "CF",
        handedness: "R",
      },
      {
        name: "Sean McCoy",
        role: "batter",
        batting: { contact: 48, power: 62, speed: 40 },
        position: "RF",
        handedness: "R",
      },
      {
        name: "Jake Flores",
        role: "batter",
        batting: { contact: 53, power: 57, speed: 40 },
        position: "DH",
        handedness: "R",
      },
    ],
    bench: [
      {
        name: "Mike Garcia",
        role: "batter",
        batting: { contact: 55, power: 55, speed: 40 },
        position: "3B",
        handedness: "R",
      },
      {
        name: "Noah Williams",
        role: "batter",
        batting: { contact: 60, power: 50, speed: 40 },
        position: "1B",
        handedness: "L",
      },
      {
        name: "Chris Baker",
        role: "batter",
        batting: { contact: 50, power: 60, speed: 40 },
        position: "LF",
        handedness: "R",
      },
      {
        name: "Sam Turner",
        role: "batter",
        batting: { contact: 52, power: 58, speed: 40 },
        position: "SS",
        handedness: "R",
      },
    ],
    pitchers: [
      // velocity + control + movement = 160
      {
        name: "Victor Cruz",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 65, control: 50, movement: 45 },
        position: "SP",
        handedness: "R",
        pitchingRole: "SP",
      },
      {
        name: "Eric Dawson",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 55, control: 60, movement: 45 },
        position: "SP",
        handedness: "R",
        pitchingRole: "SP",
      },
      {
        name: "Todd Morrison",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 50, control: 55, movement: 55 },
        position: "RP",
        handedness: "L",
        pitchingRole: "RP",
      },
      {
        name: "Jared Kim",
        role: "pitcher",
        batting: { contact: 40, power: 40, speed: 40 },
        pitching: { velocity: 60, control: 55, movement: 45 },
        position: "RP",
        handedness: "R",
        pitchingRole: "RP",
      },
    ],
  },
];
